global using System.ComponentModel;
global using System.Net;
global using SAPLink.EF;
global using Microsoft.EntityFrameworkCore;
global using SAPbobsCOM;
global using static SAPLink.Core.Enums;
global using static SAPLink.Core.InboundEnums;
global using ItemGroups = SAPLink.Core.Models.SAP.MasterData.Items.ItemGroups;
global using SAPLink.Core;
global using SAPLink.Core.Models.System;
global using ItemsHandler = SAPLink.Handler.Prism.Handlers.InboundData.Merchandise.Inventory.ItemsHandler;
global using Newtonsoft.Json;
global using RestSharp;
global using Guna.UI2.WinForms;
global using SAPLink.Core.Models;
global using SAPLink.Core.Models.Prism.Settings;
global using SAPLink.Core.Models.SAP.Documents;
global using SAPLink.Core.Models.SAP.MasterData.Items;
global using SAPLink.Core.Utilities;
global using SAPLink.Handler.Integration;
global using SAPLink.Handler.Prism.Handlers.InboundData.Merchandise.Departments;
global using SAPLink.Handler.Prism.Handlers.InboundData.Merchandise.Inventory;
global using SAPLink.Handler.Prism.Handlers.OutboundData.PointOfSale;
global using SAPLink.Handler.Prism.Handlers.OutboundData.PointOfSale.Invoice;
global using SAPLink.Handler.Prism.Handlers.OutboundData.PointOfSale.Orders;
global using SAPLink.Handler.Prism.Handlers.OutboundData.PointOfSale.Returns;
global using SAPLink.Handler.SAP.Handlers;
global using SAPLink.Utilities;
global using BusinessPartner = SAPLink.Core.Models.SAP.MasterData.BusinessPartners.BusinessPartner;
global using OutboundDocuments = SAPLink.Core.OutboundEnums.Documents;
global using Environment = System.Environment;
global using Form = System.Windows.Forms.Form;
global using PrismInvoice = SAPLink.Core.Models.Prism.Sales.Invoice;
global using SAPInvoice = SAPLink.Core.Models.SAP.Sales.Invoice;

